# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 631)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 821, 581))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Inicial = QtWidgets.QWidget()
        self.page_Inicial.setObjectName("page_Inicial")
        self.label_13 = QtWidgets.QLabel(self.page_Inicial)
        self.label_13.setGeometry(QtCore.QRect(330, 60, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page_Inicial)
        self.label_14.setGeometry(QtCore.QRect(240, 90, 421, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.btn_automatico = QtWidgets.QPushButton(self.page_Inicial)
        self.btn_automatico.setGeometry(QtCore.QRect(280, 180, 141, 23))
        self.btn_automatico.setObjectName("btn_automatico")
        self.stackedWidget.addWidget(self.page_Inicial)
        self.page_Ajuda = QtWidgets.QWidget()
        self.page_Ajuda.setObjectName("page_Ajuda")
        self.label_15 = QtWidgets.QLabel(self.page_Ajuda)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_Ajuda)
        self.label_16.setGeometry(QtCore.QRect(50, 90, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_Ajuda)
        self.label_17.setGeometry(QtCore.QRect(90, 120, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page_Ajuda)
        self.label_18.setGeometry(QtCore.QRect(90, 140, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_Ajuda)
        self.label_19.setGeometry(QtCore.QRect(90, 170, 681, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_Ajuda)
        self.label_20.setGeometry(QtCore.QRect(90, 190, 711, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_Ajuda)
        self.label_21.setGeometry(QtCore.QRect(50, 240, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.page_Ajuda)
        self.label_22.setGeometry(QtCore.QRect(90, 270, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_Ajuda)
        self.label_23.setGeometry(QtCore.QRect(90, 310, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.page_Ajuda)
        self.label_24.setGeometry(QtCore.QRect(90, 330, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.page_Ajuda)
        self.label_25.setGeometry(QtCore.QRect(90, 350, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.stackedWidget.addWidget(self.page_Ajuda)
        self.page_Cadastro = QtWidgets.QWidget()
        self.page_Cadastro.setObjectName("page_Cadastro")
        self.label = QtWidgets.QLabel(self.page_Cadastro)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.page_Cadastro)
        self.widget.setGeometry(QtCore.QRect(40, 40, 621, 401))
        self.widget.setObjectName("widget")
        self.in_cad_lote = QtWidgets.QSpinBox(self.widget)
        self.in_cad_lote.setGeometry(QtCore.QRect(190, 100, 71, 22))
        self.in_cad_lote.setObjectName("in_cad_lote")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(9, 10, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.in_cad_nome = QtWidgets.QLineEdit(self.widget)
        self.in_cad_nome.setGeometry(QtCore.QRect(149, 40, 113, 20))
        self.in_cad_nome.setObjectName("in_cad_nome")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(9, 70, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(9, 100, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 200, 71, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.in_cad_codigo = QtWidgets.QLineEdit(self.widget)
        self.in_cad_codigo.setGeometry(QtCore.QRect(149, 10, 113, 20))
        self.in_cad_codigo.setObjectName("in_cad_codigo")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(150, 200, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.in_cad_tr = QtWidgets.QLineEdit(self.widget)
        self.in_cad_tr.setGeometry(QtCore.QRect(149, 70, 113, 20))
        self.in_cad_tr.setObjectName("in_cad_tr")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(9, 40, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.in_cad_eatual = QtWidgets.QSpinBox(self.widget)
        self.in_cad_eatual.setGeometry(QtCore.QRect(191, 160, 71, 22))
        self.in_cad_eatual.setObjectName("in_cad_eatual")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setGeometry(QtCore.QRect(150, 230, 351, 101))
        self.listWidget.setObjectName("listWidget")
        self.btn_cadastrar = QtWidgets.QPushButton(self.widget)
        self.btn_cadastrar.setGeometry(QtCore.QRect(210, 360, 75, 23))
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 200, 21, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.in_cad_emin = QtWidgets.QSpinBox(self.widget)
        self.in_cad_emin.setGeometry(QtCore.QRect(191, 130, 71, 22))
        self.in_cad_emin.setObjectName("in_cad_emin")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(10, 130, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(320, 200, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.in_cad_eatual_2 = QtWidgets.QSpinBox(self.widget)
        self.in_cad_eatual_2.setGeometry(QtCore.QRect(350, 200, 51, 22))
        self.in_cad_eatual_2.setObjectName("in_cad_eatual_2")
        self.stackedWidget.addWidget(self.page_Cadastro)
        self.page_Itens = QtWidgets.QWidget()
        self.page_Itens.setObjectName("page_Itens")
        self.label_9 = QtWidgets.QLabel(self.page_Itens)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btn_novoitem = QtWidgets.QPushButton(self.page_Itens)
        self.btn_novoitem.setGeometry(QtCore.QRect(250, 550, 71, 23))
        self.btn_novoitem.setObjectName("btn_novoitem")
        self.tree_itens = QtWidgets.QTreeWidget(self.page_Itens)
        self.tree_itens.setGeometry(QtCore.QRect(20, 40, 301, 501))
        self.tree_itens.setObjectName("tree_itens")
        self.tree_itens.headerItem().setText(0, "1")
        self.stackedWidget.addWidget(self.page_Itens)
        self.page_MRP = QtWidgets.QWidget()
        self.page_MRP.setObjectName("page_MRP")
        self.label_10 = QtWidgets.QLabel(self.page_MRP)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.tableWidget = QtWidgets.QTableWidget(self.page_MRP)
        self.tableWidget.setGeometry(QtCore.QRect(20, 110, 781, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.lb_item_MRP = QtWidgets.QLabel(self.page_MRP)
        self.lb_item_MRP.setGeometry(QtCore.QRect(30, 80, 761, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.lb_item_MRP.setFont(font)
        self.lb_item_MRP.setObjectName("lb_item_MRP")
        self.label_11 = QtWidgets.QLabel(self.page_MRP)
        self.label_11.setGeometry(QtCore.QRect(350, 20, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.combo_MRP = QtWidgets.QComboBox(self.page_MRP)
        self.combo_MRP.setGeometry(QtCore.QRect(530, 20, 171, 22))
        self.combo_MRP.setObjectName("combo_MRP")
        self.btn_executar = QtWidgets.QPushButton(self.page_MRP)
        self.btn_executar.setGeometry(QtCore.QRect(720, 20, 71, 23))
        self.btn_executar.setObjectName("btn_executar")
        self.stackedWidget.addWidget(self.page_MRP)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuProdutos = QtWidgets.QMenu(self.menubar)
        self.menuProdutos.setObjectName("menuProdutos")
        self.menuMRP = QtWidgets.QMenu(self.menubar)
        self.menuMRP.setObjectName("menuMRP")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCarregar_pre_defini_es = QtWidgets.QAction(MainWindow)
        self.actionCarregar_pre_defini_es.setObjectName("actionCarregar_pre_defini_es")
        self.actionInserir_Informa_es = QtWidgets.QAction(MainWindow)
        self.actionInserir_Informa_es.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionInserir_Informa_es.setObjectName("actionInserir_Informa_es")
        self.actionCarregar_Pre_Defini_es = QtWidgets.QAction(MainWindow)
        self.actionCarregar_Pre_Defini_es.setObjectName("actionCarregar_Pre_Defini_es")
        self.actionCr_ditos = QtWidgets.QAction(MainWindow)
        self.actionCr_ditos.setObjectName("actionCr_ditos")
        self.actionRodar_Execu_o = QtWidgets.QAction(MainWindow)
        self.actionRodar_Execu_o.setObjectName("actionRodar_Execu_o")
        self.actionItens_cadastrados = QtWidgets.QAction(MainWindow)
        self.actionItens_cadastrados.setObjectName("actionItens_cadastrados")
        self.actionIn_cio = QtWidgets.QAction(MainWindow)
        self.actionIn_cio.setObjectName("actionIn_cio")
        self.actionAjuda = QtWidgets.QAction(MainWindow)
        self.actionAjuda.setObjectName("actionAjuda")
        self.menuArquivo.addAction(self.actionIn_cio)
        self.menuArquivo.addAction(self.actionAjuda)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionCr_ditos)
        self.menuProdutos.addAction(self.actionItens_cadastrados)
        self.menuProdutos.addAction(self.actionInserir_Informa_es)
        self.menuProdutos.addSeparator()
        self.menuProdutos.addAction(self.actionCarregar_Pre_Defini_es)
        self.menuMRP.addAction(self.actionRodar_Execu_o)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuProdutos.menuAction())
        self.menubar.addAction(self.menuMRP.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MRP Systema"))
        self.label_13.setText(_translate("MainWindow", "MRP"))
        self.label_14.setText(_translate("MainWindow", "Material Requirements Planning"))
        self.btn_automatico.setText(_translate("MainWindow", "Auto Execução"))
        self.label_15.setText(_translate("MainWindow", "Ajuda"))
        self.label_16.setText(_translate("MainWindow", "Para executar o MRP:"))
        self.label_17.setText(_translate("MainWindow", "Clique em \"Produtos\" > \"Carregar Pré-Definições\""))
        self.label_18.setText(_translate("MainWindow", "Depois em \"MRP\" > \"Executar\""))
        self.label_19.setText(_translate("MainWindow", "Quando estiver na página do MRP, selecione o item desejado e clique em \"Executar\""))
        self.label_20.setText(_translate("MainWindow", "assim, você verá a execução do MRP para o determinado item nas próximas 12 semanas"))
        self.label_21.setText(_translate("MainWindow", "Para ver os itens cadastrados:"))
        self.label_22.setText(_translate("MainWindow", "Clique em \"Produtos\" > \"Itens cadastrados\""))
        self.label_23.setText(_translate("MainWindow", "Você terá a visualização dos itens inseridos no sistema numa visão identada"))
        self.label_24.setText(_translate("MainWindow", "onde cada nível superior é representado como pai de um nível inferior"))
        self.label_25.setText(_translate("MainWindow", "sendo exibido em forma de árvore"))
        self.label.setText(_translate("MainWindow", "Cadastro de Item"))
        self.label_7.setText(_translate("MainWindow", "Quantidade em Estoque"))
        self.label_2.setText(_translate("MainWindow", "Código"))
        self.label_5.setToolTip(_translate("MainWindow", "Tempo de Ressuprimento"))
        self.label_5.setText(_translate("MainWindow", "TR - (Lead Time)"))
        self.label_6.setText(_translate("MainWindow", "Lote Mínimo"))
        self.pushButton_3.setText(_translate("MainWindow", "Incluir"))
        self.label_3.setText(_translate("MainWindow", "Nome"))
        self.label_4.setToolTip(_translate("MainWindow", "Depende de quais itens"))
        self.label_4.setText(_translate("MainWindow", "Dependências"))
        self.btn_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.pushButton_4.setText(_translate("MainWindow", "-"))
        self.label_8.setText(_translate("MainWindow", "Estoque Mínimo"))
        self.label_12.setToolTip(_translate("MainWindow", "Depende de quais itens"))
        self.label_12.setText(_translate("MainWindow", "Qtd:"))
        self.label_9.setText(_translate("MainWindow", "Itens Cadastrados"))
        self.btn_novoitem.setText(_translate("MainWindow", "Novo item"))
        self.label_10.setText(_translate("MainWindow", "MRP"))
        self.lb_item_MRP.setText(_translate("MainWindow", "MRP"))
        self.label_11.setText(_translate("MainWindow", "Item para executar o MRP:"))
        self.btn_executar.setText(_translate("MainWindow", "Executar"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuProdutos.setTitle(_translate("MainWindow", "Produtos"))
        self.menuMRP.setTitle(_translate("MainWindow", "MRP"))
        self.actionCarregar_pre_defini_es.setText(_translate("MainWindow", "Carregar pre-definições"))
        self.actionInserir_Informa_es.setText(_translate("MainWindow", "Cadastrar itens"))
        self.actionInserir_Informa_es.setStatusTip(_translate("MainWindow", "Permite o cadastro de um novo item"))
        self.actionInserir_Informa_es.setWhatsThis(_translate("MainWindow", "Permite o cadastro de um novo item"))
        self.actionCarregar_Pre_Defini_es.setText(_translate("MainWindow", "Carregar Pré-Definições"))
        self.actionCarregar_Pre_Defini_es.setStatusTip(_translate("MainWindow", "Insere produtos no sistema"))
        self.actionCarregar_Pre_Defini_es.setWhatsThis(_translate("MainWindow", "Insere produtos no sistema"))
        self.actionCr_ditos.setText(_translate("MainWindow", "Créditos"))
        self.actionCr_ditos.setStatusTip(_translate("MainWindow", "Créditos"))
        self.actionCr_ditos.setWhatsThis(_translate("MainWindow", "Créditos"))
        self.actionRodar_Execu_o.setText(_translate("MainWindow", "Executar"))
        self.actionRodar_Execu_o.setStatusTip(_translate("MainWindow", "Executa uma rodada do MRP para um dado item"))
        self.actionRodar_Execu_o.setWhatsThis(_translate("MainWindow", "Executa uma rodada do MRP para um dado item"))
        self.actionItens_cadastrados.setText(_translate("MainWindow", "Itens cadastrados"))
        self.actionItens_cadastrados.setToolTip(_translate("MainWindow", "Exibe relatório de itens já inseridos no sistema"))
        self.actionItens_cadastrados.setStatusTip(_translate("MainWindow", "Exibe relatório de itens já inseridos no sistema"))
        self.actionItens_cadastrados.setWhatsThis(_translate("MainWindow", "Exibe relatório de itens já inseridos no sistema"))
        self.actionIn_cio.setText(_translate("MainWindow", "Início"))
        self.actionAjuda.setText(_translate("MainWindow", "Ajuda"))

