# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 631)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 821, 581))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Inicial = QtWidgets.QWidget()
        self.page_Inicial.setObjectName("page_Inicial")
        self.pushButton = QtWidgets.QPushButton(self.page_Inicial)
        self.pushButton.setGeometry(QtCore.QRect(410, 190, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_Inicial)
        self.page_Cadastro = QtWidgets.QWidget()
        self.page_Cadastro.setObjectName("page_Cadastro")
        self.label = QtWidgets.QLabel(self.page_Cadastro)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.page_Cadastro)
        self.widget.setGeometry(QtCore.QRect(40, 40, 461, 401))
        self.widget.setObjectName("widget")
        self.in_cad_lote = QtWidgets.QSpinBox(self.widget)
        self.in_cad_lote.setGeometry(QtCore.QRect(190, 100, 71, 22))
        self.in_cad_lote.setObjectName("in_cad_lote")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(9, 10, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.in_cad_nome = QtWidgets.QLineEdit(self.widget)
        self.in_cad_nome.setGeometry(QtCore.QRect(149, 40, 113, 20))
        self.in_cad_nome.setObjectName("in_cad_nome")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(9, 70, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(9, 100, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 200, 71, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.in_cad_codigo = QtWidgets.QLineEdit(self.widget)
        self.in_cad_codigo.setGeometry(QtCore.QRect(149, 10, 113, 20))
        self.in_cad_codigo.setObjectName("in_cad_codigo")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(150, 200, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.in_cad_tr = QtWidgets.QLineEdit(self.widget)
        self.in_cad_tr.setGeometry(QtCore.QRect(149, 70, 113, 20))
        self.in_cad_tr.setObjectName("in_cad_tr")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(9, 40, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.in_cad_eatual = QtWidgets.QSpinBox(self.widget)
        self.in_cad_eatual.setGeometry(QtCore.QRect(191, 160, 71, 22))
        self.in_cad_eatual.setObjectName("in_cad_eatual")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setGeometry(QtCore.QRect(150, 230, 261, 101))
        self.listWidget.setObjectName("listWidget")
        self.btn_cadastrar = QtWidgets.QPushButton(self.widget)
        self.btn_cadastrar.setGeometry(QtCore.QRect(130, 370, 75, 23))
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(391, 200, 21, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.in_cad_emin = QtWidgets.QSpinBox(self.widget)
        self.in_cad_emin.setGeometry(QtCore.QRect(191, 130, 71, 22))
        self.in_cad_emin.setObjectName("in_cad_emin")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(10, 130, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.page_Cadastro)
        self.page_Itens = QtWidgets.QWidget()
        self.page_Itens.setObjectName("page_Itens")
        self.label_9 = QtWidgets.QLabel(self.page_Itens)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.tree_itens = QtWidgets.QTreeView(self.page_Itens)
        self.tree_itens.setGeometry(QtCore.QRect(20, 40, 301, 501))
        self.tree_itens.setObjectName("tree_itens")
        self.btn_novoitem = QtWidgets.QPushButton(self.page_Itens)
        self.btn_novoitem.setGeometry(QtCore.QRect(250, 550, 71, 23))
        self.btn_novoitem.setObjectName("btn_novoitem")
        self.stackedWidget.addWidget(self.page_Itens)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuProdutos = QtWidgets.QMenu(self.menubar)
        self.menuProdutos.setObjectName("menuProdutos")
        self.menuMRP = QtWidgets.QMenu(self.menubar)
        self.menuMRP.setObjectName("menuMRP")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCarregar_pre_defini_es = QtWidgets.QAction(MainWindow)
        self.actionCarregar_pre_defini_es.setObjectName("actionCarregar_pre_defini_es")
        self.actionInserir_Informa_es = QtWidgets.QAction(MainWindow)
        self.actionInserir_Informa_es.setObjectName("actionInserir_Informa_es")
        self.actionCarregar_Pre_Defini_es = QtWidgets.QAction(MainWindow)
        self.actionCarregar_Pre_Defini_es.setObjectName("actionCarregar_Pre_Defini_es")
        self.actionCr_ditos = QtWidgets.QAction(MainWindow)
        self.actionCr_ditos.setObjectName("actionCr_ditos")
        self.actionRodar_Execu_o = QtWidgets.QAction(MainWindow)
        self.actionRodar_Execu_o.setObjectName("actionRodar_Execu_o")
        self.actionItens_cadastrados = QtWidgets.QAction(MainWindow)
        self.actionItens_cadastrados.setObjectName("actionItens_cadastrados")
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionCr_ditos)
        self.menuProdutos.addAction(self.actionItens_cadastrados)
        self.menuProdutos.addAction(self.actionInserir_Informa_es)
        self.menuProdutos.addSeparator()
        self.menuProdutos.addAction(self.actionCarregar_Pre_Defini_es)
        self.menuMRP.addAction(self.actionRodar_Execu_o)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuProdutos.menuAction())
        self.menubar.addAction(self.menuMRP.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MRP Systema"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "Cadastro de Item"))
        self.label_7.setText(_translate("MainWindow", "Quantidade em Estoque"))
        self.label_2.setText(_translate("MainWindow", "Código"))
        self.label_5.setToolTip(_translate("MainWindow", "Tempo de Ressuprimento"))
        self.label_5.setText(_translate("MainWindow", "TR - (Lead Time)"))
        self.label_6.setText(_translate("MainWindow", "Lote Mínimo"))
        self.pushButton_3.setText(_translate("MainWindow", "Incluir"))
        self.label_3.setText(_translate("MainWindow", "Nome"))
        self.label_4.setToolTip(_translate("MainWindow", "Depende de quais itens"))
        self.label_4.setText(_translate("MainWindow", "Dependências"))
        self.btn_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.pushButton_4.setText(_translate("MainWindow", "-"))
        self.label_8.setText(_translate("MainWindow", "Estoque Mínimo"))
        self.label_9.setText(_translate("MainWindow", "Itens Cadastrados"))
        self.btn_novoitem.setText(_translate("MainWindow", "Novo item"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuProdutos.setTitle(_translate("MainWindow", "Produtos"))
        self.menuMRP.setTitle(_translate("MainWindow", "MRP"))
        self.actionCarregar_pre_defini_es.setText(_translate("MainWindow", "Carregar pre-definições"))
        self.actionInserir_Informa_es.setText(_translate("MainWindow", "Cadastrar itens"))
        self.actionCarregar_Pre_Defini_es.setText(_translate("MainWindow", "Carregar Pré-Definições"))
        self.actionCr_ditos.setText(_translate("MainWindow", "Créditos"))
        self.actionRodar_Execu_o.setText(_translate("MainWindow", "Rodar Execução"))
        self.actionItens_cadastrados.setText(_translate("MainWindow", "Itens cadastrados"))
        self.actionItens_cadastrados.setToolTip(_translate("MainWindow", "Exibe relatório de itens já inseridos no sistema"))
        self.actionItens_cadastrados.setStatusTip(_translate("MainWindow", "Exibe relatório de itens já inseridos no sistema"))
        self.actionItens_cadastrados.setWhatsThis(_translate("MainWindow", "Exibe relatório de itens já inseridos no sistema"))

